// <auto-generated />
namespace EF_CODEFİRST2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tabloOlustur1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tabloOlustur1));
        
        string IMigrationMetadata.Id
        {
            get { return "202208311927255_tabloOlustur1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
